#!/usr/bin/env node
/**
 * pnpm auto:test-gen (M6 MVP) — independent test generator.
 *
 * Per AGENT-ROSTER-AUDIT.md M6: 'Test-generator agent independent of impl
 * worker. Catches the tests-pass-because-they-test-the-impl-not-the-spec
 * bug.' Phase 2 needs L1 formal contracts + L4 mutation testing infra to
 * be fully effective.
 *
 * THIS MVP: takes a task pack's acceptance_criteria (NL strings) + outputs
 * a property-based test STUB file with one TODO per AC. The stubs are
 * intentionally not auto-passing; operator (or impl worker on round 2)
 * must fill in the test logic. Better than nothing — at least every AC
 * has a tracked test stub.
 *
 * Phase 2 will add:
 *   - L1 formal-contract parsing: each AC = a Hoare triple or property-
 *     based predicate, extracted from FRD §8 ACs
 *   - fast-check property generation from typed AC predicates
 *   - L4 mutation testing harness invocation
 *   - Independent verifier model (different from impl worker) reviews
 *     generated tests against the FRD AC spec
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readTaskPack, evidenceDir } from '../lib/runState';
import { harnessRoot } from '../lib/harnessRoot';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const HARNESS_ROOT = harnessRoot();

interface Args {
  taskId: string;
  applyMode: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { taskId: '', applyMode: false };
  const positional: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--apply') args.applyMode = true;
    else if (!a.startsWith('--')) positional.push(a);
  }
  if (positional.length < 1) throw new Error('Required: <task_id>');
  args.taskId = positional[0];
  return args;
}

function findRunForTask(taskId: string): string {
  const runsDir = path.join(HARNESS_ROOT, '.agent-runs');
  if (!fs.existsSync(runsDir)) throw new Error(`No .agent-runs/`);
  for (const r of fs.readdirSync(runsDir)) {
    if (fs.existsSync(path.join(runsDir, r, 'tasks', `${taskId}.json`))) return r;
  }
  throw new Error(`Task ${taskId} not found`);
}

/**
 * R5 fail-safe: AC text comes from arbitrary FRD authors and may contain
 * characters that break TS line comments (CR/LF) or single-quoted string
 * literals (', \, CR/LF). Escape both contexts so the generated stub always
 * compiles, regardless of AC content.
 */
function escForLineComment(s: string, max: number): string {
  return s.slice(0, max).replace(/[\r\n]+/g, ' ');
}

function escForSingleQuoted(s: string, max: number): string {
  return s
    .slice(0, max)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/[\r\n]+/g, ' ');
}

function generateTestStub(taskId: string, module: string, acs: string[]): string {
  const moduleSlug = module.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const taskIdQuoted = escForSingleQuoted(taskId, 100);
  const moduleSlugQuoted = escForSingleQuoted(moduleSlug, 100);
  return `/**
 * AUTO-GENERATED test stub for ${escForLineComment(taskId, 100)} (${escForLineComment(module, 100)}).
 *
 * Generated by pnpm auto:test-gen at ${new Date().toISOString()}.
 *
 * STATUS: STUB — every test below has a TODO. Operator (or impl worker
 * round 2) MUST fill in the test logic. Phase 2 will add automatic
 * property-based test generation from formal AC predicates (L1 formal
 * contracts).
 *
 * Phase 1 limitation: the AC strings below are natural-language
 * descriptions parsed from the task pack, NOT testable predicates.
 * Tests will fail by design (xtest('TODO')) until filled in.
 */
import { describe, test, expect } from 'vitest';

describe('${moduleSlugQuoted} — ${taskIdQuoted}', () => {
${acs.map((ac, i) => `  // AC #${i + 1}: ${escForLineComment(ac, 200)}
  test.todo('AC#${i + 1}: ${escForSingleQuoted(ac, 80)}'); // TODO: implement test for: ${escForLineComment(ac, 200)}
`).join('\n')}});
`;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const runId = findRunForTask(args.taskId);
  const pack = readTaskPack(runId, args.taskId);

  if (pack.acceptance_criteria.length === 0) {
    console.log(`No acceptance_criteria on task pack; nothing to generate.`);
    process.exit(0);
  }

  const acStrings = pack.acceptance_criteria.map((ac) => typeof ac === 'string' ? ac : ac.text);
  const stub = generateTestStub(args.taskId, pack.module_or_sprint, acStrings);
  const evDir = evidenceDir(runId, args.taskId);
  const stubPath = path.join(evDir, 'test-gen.stub.test.ts');

  if (args.applyMode) {
    if (!fs.existsSync(evDir)) fs.mkdirSync(evDir, { recursive: true });
    fs.writeFileSync(stubPath, stub);
    console.log(`✓ wrote ${stubPath} (${pack.acceptance_criteria.length} AC stubs)`);
    console.log(``);
    console.log(`Phase 1 MVP limitations (deferred to Phase 2):`);
    console.log(`  - Stubs are NL-parsed; need L1 formal-contract predicates for real generation`);
    console.log(`  - No fast-check property tests (Phase 2)`);
    console.log(`  - No L4 mutation testing harness (Phase 3)`);
    console.log(`  - No independent verifier model (Phase 2)`);
  } else {
    console.log(`[dry-run] Would write ${stubPath}:`);
    console.log(``);
    console.log(stub);
    console.log(``);
    console.log(`Pass --apply to actually write the stub.`);
  }
}

main();
